image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - scalameta.metals
    - scala-lang.scala
    - github.vscode-pull-request-github
    - vscodevim.vim
    - usernamehw.errorlens
    - mishkinf.goto-next-previous-member
    - oderwat.indent-rainbow
    - baccata.scaladex-search
